name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout source
            uses: actions/checkout@v4
          - name: Set up JDK 21
            uses: actions/setup-java@v4
            with:
              java-version: '21'
              distribution: 'temurin'
              cache: maven
          - name: Build with Maven
            run: mvn clean install
          - name: Login to Docker Hub
            run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - name: Build Docker image
            run: docker build -t ${{ secrets.DOCKER_USERNAME }}/beer-brewery-basic .
          - name: Push Docker image to Docker hub
            run: docker push ${{ secrets.DOCKER_USERNAME }}/beer-brewery-basic:latest

    deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: Pull Image from Docker Hub
          run: docker pull anil0331/beer-brewery-basic:latest
        - name: Delete old container
          run: docker rm -f beer-brewery-basic
        - name: Run docker container
          run: docker run -d -p 8080:8080 --name beer-brewery-basic anil0331/beer-brewery-basic:latest



