name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout source
            uses: actions/checkout@v4
          - name: Set up JDK 21
            uses: actions/setup-java@v4
            with:
              java-version: '21'
              distribution: 'temurin'
              cache: maven
          - name: Build with Maven
            run: mvn clean install
          - name: Login to Docker Hub
            run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          - name: Build Docker image
            run: docker build -t ${{ secrets.DOCKER_USERNAME }}/beer-brewery-basic .
          - name: Push Docker image to Docker hub
            run: docker push ${{ secrets.DOCKER_USERNAME }}/beer-brewery-basic:latest





